services:
  - type: web
    name: hostel-management-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: hostel-management-hostelportal.j.aivencloud.com
      - key: DB_PORT
        value: "22615"
      - key: DB_NAME
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_MODE
        value: REQUIRED
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://hostel-management-mit.vercel.app
